CREATE TABLE JOBS (
  URI TEXT,
  SCRIPT TEXT,
  USER TEXT,
  JOB_DIR TEXT,
  INPUTS TEXT,
  LABEL TEXT,
  JOB_STATUS TEXT,
  EXEC_DIR TEXT,
  CREATED_AT DATETIME,
  MODIFIED_AT DATETIME,
  ERROR_MSG TEXT
);