CREATE TABLE JOBS (
  URI TEXT,
  SCRIPT TEXT,
  USER TEXT,
  JOB_DIR TEXT,
  LABEL TEXT,
  JOB_STATUS TEXT,
  EXEC_DIR TEXT,
  CREATED_AT DATETIME,
  MODIFIED_AT DATETIME,
  ERROR_MSG TEXT,
  SCRIPT_PATH TEXT,
  SCRIPT_ARGS TEXT,
  CHANNEL_URI TEXT,
  RETURN_CODE INT
);